Check html semantics and stlying
inspecta/personal-portfolio pull request #2
Opened 2022-08-18 14:46 UTC by inspecta

This is a portfolio mobile first replica of a web template at Figma.
I have included linters, images, stylesheets, boxicons and a project license.
Checkout my HTML and CSS writing, use of HTML semantics and position of elements plus my stylings.

2022-08-18 14:55 UTC, BertrandConxy commented
Hello @inspecta Please make sure that all linters are passing 😃 👍

2022-08-18 15:45 UTC, BertrandConxy reviewed
Hi @inspecta , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔴 

You have submitted a project, that has some linter errors


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-18 18:54 UTC, Kamba56 requested changes
Hi @inspecta, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [ ] linters passed all checks
- [ ] Professional Readme
- [ ] Descriptive PR description

## Required Changes ♻️
_Please check the comments under the review for suggested changes._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 18:54 UTC, Kamba56 commented on index.html
> +        </div>
- [ ] Kindly use an unordered list to list social icons. This is best practice for HTML semantics.

2022-08-18 18:54 UTC, Kamba56 commented on index.html
> +          <p class="logo">M.D</p>
- [ ] Kindly consider using an `<a>` to wrap your logo. This is best practice and it is [standard convention](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page).

2022-08-18 18:54 UTC, Kamba56 commented on index.html
> +          <img class="menu-btn" src="/images/menu-btn.svg" alt="Menu Button" />
- [ ] Kindly check the link to your hamburger icon as the icon doesn't display on the webpage.

2022-08-18 18:54 UTC, Kamba56 commented on index.html
> +      </main>
- [ ] Kindly use a `<section>` element to wrap the headline section as this is convention for HTML5 semantics.

- [ ] Please add the background image to this section as it is in the template.

2022-08-18 18:54 UTC, Kamba56 commented on index.html
> +        </div>
- [ ] Please note that this is also part of the headline section. Kindly move it to the section.

2022-08-18 21:37 UTC, Kamba56 requested changes
Hi @inspecta, 

Great work on making the changes requested by a previous reviewer 👏
 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [ ] Meanignful commit messages
- [ ] All linters checks passed
- [ ] Descriptive PR summary

 ## Required Changes ♻️
- Please in all future projects, kindly make sure that your branch name should have a name of a feature or action implemented in the branch and your PR title should be a short summary of the changes implemented in the PR.
 
_Kindly check the comments under the review for suggested changes._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 21:37 UTC, Kamba56 commented on index.html
> -        </div>
- [ ] As requested by the previous reviewer, kindly add a background image to this section to match the design template.
*Your project*![ccc](https://user-images.githubusercontent.com/94551484/185498189-6ff8e31a-0fa2-40c6-a78a-836d8d446e03.png)
*Design template*![aaa](https://user-images.githubusercontent.com/94551484/185498217-ae5e1d9f-6f97-40dc-9748-f4cbc026e905.png)

- [ ] Kindly change your alignments to match the design template. Please note that your project design should look exactly like the Figma template you chose.

2022-08-19 13:51 UTC, aimemalaika approved these changes
Hi @inspecta, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉

- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 15:19 UTC, merged